apiVersion: 1

datasources:
  - name: ThreatDB
    uid: threatdb
    type: postgres
    access: proxy
    url: threat_db:5432
    database: threatdb
    user: threat
    secureJsonData:
      password: threat
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
